import { ArrowDown, MoveUpRight, Layers, GitBranch, ScanLine } from "lucide-react";
import { Eyebrow, ButtonLink, SectionTitle, TextLink } from "@/components/ui";
import { HwmVisual } from "@/components/hwm-visual";
import { Architecture, ObservationComparison } from "@/components/diagrams";
import { Publications } from "@/components/publications";
import { Collaboration } from "@/components/footer";
import { pageMetadata } from "@/lib/metadata";
export const metadata = pageMetadata("Physical Intelligence Research", "We develop Haptic World Models that learn to predict how physical interactions evolve under action.", "/");
export default function Home() { return <>
 <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><Eyebrow>PHYSICAL INTELLIGENCE RESEARCH</Eyebrow><h1>Teaching AI to<br/>Understand<br/><span>Physical Interaction.</span></h1><p className="hero-lede">We develop Haptic World Models that learn to predict how physical interactions evolve under action.</p><div className="hero-actions"><ButtonLink href="/research">Explore Our Research</ButtonLink><TextLink href="/research/haptic-world-models">Haptic World Models</TextLink></div><p className="hero-note"><span className="status-dot"/> A new perspective on embodied intelligence</p></div><HwmVisual/></div><div className="shell hero-bottom"><span>FROM OBSERVATION TO UNDERSTANDING</span><div>Experience <span>→</span> Interaction state <span>→</span> Physical futures</div><a href="#problem" aria-label="Explore the physical intelligence research below"><ArrowDown size={18}/></a></div></section>
 <section className="section shell" id="problem"><SectionTitle number="01" label="THE PHYSICAL WORLD" title="Beyond What the World Looks Like."><p>The same visible motion can conceal very different physical realities. Contact-rich decisions require understanding what happens beneath the surface.</p></SectionTitle><ObservationComparison/></section>
 <section className="section tinted"><div className="shell"><SectionTitle number="02" label="HAPTIC WORLD MODELS" title="Modeling Interaction, Not Just Observation."><p>A world model for the way we act on the world. Our research focuses on three connected capabilities.</p></SectionTitle><div className="capability-grid">{[{icon:ScanLine,title:"Understand interaction state",text:"Represent contact, force, resistance, and constraints as physically meaningful states."},{icon:GitBranch,title:"Predict physical futures",text:"Anticipate how those states may evolve under different candidate actions."},{icon:Layers,title:"Support adaptive decisions",text:"Use predicted interaction to inform planning, correction, and the next action."}].map((item,index)=><article key={item.title}><div className="capability-top"><item.icon size={26} strokeWidth={1.2} aria-hidden="true"/><span className="mono">0{index+1}</span></div><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
 <section className="section shell"><SectionTitle number="03" label="THE RESEARCH FRAMEWORK" title="Experience. Predict. Adapt."><p>From multimodal observations to action-conditioned prediction—a conceptual framework for physical intelligence.</p></SectionTitle><Architecture/></section>
 <section className="section experience"><div className="shell experience-grid"><div className="experience-visual" aria-hidden="true"><div className="experience-orbit"><span>HUMAN</span><div className="orbit-core">Physical<br/>experience</div><span>ROBOT</span></div><div className="signal-legend"><span>Motion</span><span>Touch</span><span>Force</span><span>Correction</span></div><p className="mono">CROSS-EMBODIMENT LEARNING / RESEARCH DIRECTION</p></div><div><p className="section-label">04 / SENSORIMOTOR LEARNING</p><h2>Learning from<br/>Physical Experience.</h2><p>Human motion, touch, force, and action correction may offer rich supervision for learning how the physical world responds.</p><p>Alongside robot interaction data, we investigate how this experience can shape useful representations across embodiments. Human-to-robot transfer remains an open research challenge.</p><TextLink href="/research/haptic-world-models#sensorimotor">Our research perspective</TextLink></div></div></section>
 <section className="section shell"><SectionTitle number="05" label="RESEARCH & PUBLICATIONS" title="Ideas for a Physical Intelligence."><TextLink href="/research">Explore all research</TextLink></SectionTitle><Publications/></section>
 <section className="section model-home tinted"><div className="shell split"><div><p className="section-label">06 / MODEL DEVELOPMENT</p><h2>Building Models for<br/>Physical Intelligence.</h2><p>Haptic World Models are our core AI model direction. We are developing the foundations for predictive representations of physical interaction.</p><TextLink href="/models">Explore our model direction</TextLink></div><div className="model-preview"><div className="model-preview-top"><span className="mono">MODEL FAMILY / HWM</span><MoveUpRight size={21} aria-hidden="true"/></div><div className="model-glyph" aria-hidden="true">{Array.from({length:7},(_,i)=><i key={i} style={{transform:`rotate(${i*25}deg)`}}/>)}</div><h3>Haptic World Models</h3><div className="model-preview-bottom"><span className="tag"><span className="status-dot"/> Research direction</span><span>No public release announced</span></div></div></div></section>
 <section className="section shell about-home"><p className="section-label">07 / PERSPECTRA ROBOTICS</p><h2>A research company.<br/>A physical perspective.</h2><div><p>We are a research-driven AI company advancing predictive physical intelligence. Our mission is to build models that help embodied systems anticipate the consequences of their actions.</p><TextLink href="/about">Meet Perspectra</TextLink></div></section><Collaboration/>
 </>; }
